name: Deploy_Snowflake_Code

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Snowflake CLI
        uses: snowflakedb/snowflake-actions/setup-snowflake-cli@v1
        with:
          snowflake-account: ${{ secrets.SF_ACCOUNT }}
          snowflake-warehouse: ${{ secrets.SF_WAREHOUSE }}
          snowflake-role: ${{ secrets.SF_ROLE }}
          snowflake-database: ${{ secrets.SF_DATABASE }}
          snowflake-schema: ${{ secrets.SF_SCHEMA }}
          snowflake-username: ${{ secrets.SF_USERNAME }}
          snowflake-password: ${{ secrets.SF_PASSWORD }}

      - name: Deploy Snowflake Code
        run: |
          snowsql -f sql/test_view.sql
