name: Deploy_Snowflake_Code

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Snowflake CLI
        run: |
            curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.12-linux_x86_64.bash
            bash snowsql-1.2.12-linux_x86_64.bash
            echo 'export PATH=~/snowsql:$PATH' >> ~/.bashrc
            source ~/.bashrc
  
      - name: Deploy Snowflake Code
        run: |
          snowsql -a ${{ secrets.SF_ACCOUNT }} \
                  -w ${{ secrets.SF_WAREHOUSE }} \
                  -r ${{ secrets.SF_ROLE }} \
                  -d ${{ secrets.SF_DATABASE }} \
                  -s ${{ secrets.SF_SCHEMA }} \
                  -u ${{ secrets.SF_USERNAME }} \
                  -p ${{ secrets.SF_PASSWORD }} \
                  -f sql/test_view.sql
